### PR TITLE
add ci-kubeconform action

### PR DESCRIPTION
**Pull request by momentmaker**
This adds a new action `ci-kubeconform`.

Tested here:
https://github.com/smartcontractkit/chainlink/actions/runs/8740607631?pr=12865

### CODE REVIEW

**Comment by chainchad** [comment]
Looks like CI is failing [here](https://github.com/smartcontractkit/chainlink/actions/runs/8727023228/job/23943581188?pr=12865). Was there another, successful run?

**Comment by momentmaker** [comment]
> Looks like CI is failing [here](https://github.com/smartcontractkit/chainlink/actions/runs/8727023228/job/23943581188?pr=12865). Was there another, successful run?

ahh it's failing because our chart/manifests have to be fixed :)

**Comment by momentmaker** [comment]
ok I did it another way and that seems to work:
https://github.com/smartcontractkit/chainlink/actions/runs/8728699447?pr=12865

I'll need to clean it up better and move the `helm repo add` into this action as well as the `ci-lint-chart` action.

**Comment by momentmaker** [comment]
cool I just updated both actions to include `add helm repos` step and they work :)
https://github.com/smartcontractkit/chainlink/actions/runs/8740607631?pr=12865

**Review by chainchad — APPROVED** [review]

**Pull request merged**
